# NodeJS Version 20.9
FROM node:20.9-buster-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install

# Set Env
ENV NODE_ENV development

EXPOSE 8080

# Cmd script
CMD ["npm", "run", "dev"]
