FROM node:20.9-alpine3.17

RUN apk --no-cache add dumb-init

RUN mkdir -p /home/node/app && chown node:node /home/node/app 

WORKDIR /home/node/app

USER node

RUN mkdir tmp

COPY --chown=node:node . .

RUN npm ci

ENV NODE_ENV development

EXPOSE 8080

# Cmd script
CMD [ "dumb-init", "npm", "run", "dev" ]
